### ISSUE TITLE
Weak Hyperscientific gets stuck formatting `(e^9e15)1`

### ISSUE THREAD

**Issue by James103** [MathCookie17/Eternal-Notations#18]
When formatting `(e^9e15)1`, Weak Hyperscientific gets stuck in an infinite loop, equivalent to this while loop:
https://github.com/MathCookie17/Eternal-Notations/blob/008fbcf9aefcebad7af2232b6ffdbbe3850a6bed/src/notations/weakHyperscientific.ts#L116-L119

`value` is NaN while `added_es` starts at 4.5e15 and endlessly increments.

**Comment by MathCookie17** [comment]
Man, how do I keep missing these?

I think I need to test specifically F9e15 before posting _any_ update because that's where most of the errors seem to be coming from.
