### ISSUE TITLE
`PrestigeLayerNotation`: unrounded `getLayer` returns 0 for results less than 10.

### ISSUE THREAD

**Issue by James103** [MathCookie17/Eternal-Notations#9]
For a project of mine (similar to True Infinity), I need to estimate how many prestige layers would a given amount of antimatter / points get me. I am using the `getLayer` method of `PrestigeLayerNotation` to achieve this, with `rounded` being false in order to account for partial progress to the next layer.

However, the `getLayer` method of `PrestigeLayerNotation`, when called with `rounded` being false, will return 0 if the whole number part of the layer would be less than 10. In other words, if `new EternalNotations.PrestigeLayerNotation(...).getLayer(x, true)` returns a number less than 10, `new EternalNotations.PrestigeLayerNotation(...).getLayer(x, false)` will return 0.

Is there any way this can be fixed? Meanwhile, a workaround I'm using involves a linear approximation based on the currency amount on the highest prestige layer.

To test, run the following command:
```js
[
new EternalNotations.PrestigeLayerNotation(Math.log10(Number.MAX_VALUE), Number.MAX_VALUE).getLayer(new Decimal("ee24.891"), true).toString(),
new EternalNotations.PrestigeLayerNotation(Math.log10(Number.MAX_VALUE), Number.MAX_VALUE).getLayer(new Decimal("ee24.891"), false).toString(),
new EternalNotations.PrestigeLayerNotation(Math.log10(Number.MAX_VALUE), Number.MAX_VALUE).getLayer(new Decimal("ee24.89"), true).toString(),
new EternalNotations.PrestigeLayerNotation(Math.log10(Number.MAX_VALUE), Number.MAX_VALUE).getLayer(new Decimal("ee24.89"), false).toString()
]
```
I got this output:
```js
[
"10",
"10.000197491316428",
"9",
"0"
]
````
The correct output should have the last entry being closer to 10 than 9, but still less than 10.

**Comment by MathCookie17** [comment]
Fixed. Prestige Layer notation is unfortunately not very well-tested at the moment (it's the only notation to include its own public utility functions, but most of my testing has been on notation parameters and presets), so perhaps your project will help with that...
